// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX1698mNzGRxn66uCTk3T9Hk4NBk9chH0',
    appId: '1:231788750983:web:c5ee4b87f51f100a1e3022',
    messagingSenderId: '231788750983',
    projectId: 'flutter-auth-app-d9922',
    authDomain: 'flutter-auth-app-d9922.firebaseapp.com',
    storageBucket: 'flutter-auth-app-d9922.firebasestorage.app',
    measurementId: 'G-FGHYGPBYNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXrFEhevg_u1YMZ0Q3EWFYNbsiHD5jY9o',
    appId: '1:231788750983:android:d951fbb47b3db3d71e3022',
    messagingSenderId: '231788750983',
    projectId: 'flutter-auth-app-d9922',
    storageBucket: 'flutter-auth-app-d9922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZNdUe32cDWEIJCYrMet3Xo10sw0-i-I',
    appId: '1:231788750983:ios:92aae8f4936b488b1e3022',
    messagingSenderId: '231788750983',
    projectId: 'flutter-auth-app-d9922',
    storageBucket: 'flutter-auth-app-d9922.firebasestorage.app',
    iosBundleId: 'com.example.lr16FirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ZNdUe32cDWEIJCYrMet3Xo10sw0-i-I',
    appId: '1:231788750983:ios:92aae8f4936b488b1e3022',
    messagingSenderId: '231788750983',
    projectId: 'flutter-auth-app-d9922',
    storageBucket: 'flutter-auth-app-d9922.firebasestorage.app',
    iosBundleId: 'com.example.lr16FirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX1698mNzGRxn66uCTk3T9Hk4NBk9chH0',
    appId: '1:231788750983:web:6ee9fcbffe37deb31e3022',
    messagingSenderId: '231788750983',
    projectId: 'flutter-auth-app-d9922',
    authDomain: 'flutter-auth-app-d9922.firebaseapp.com',
    storageBucket: 'flutter-auth-app-d9922.firebasestorage.app',
    measurementId: 'G-33BXF9VH50',
  );
}
